import { type Activity } from "../components/activities/types"
export const mockActivities: Activity[] = [
  {
    id: 'a1',
    title: 'Pilates',
    date: '2025-11-13',
    startTime: '10:00',
    endTime: '10:40',
    location: "Makers Corner",
    image: '/assets/pilates.jpg',
  },
  {
    id: 'a2',
    title: 'Styrke & Sundhed',
    date: '2025-11-12',
    startTime: '14:00',
    endTime: '16:00',
    location: 'RMI, Store Møllevej 5',
    image: '/assets/gym1.jpg',
  },
  {
    id: 'a3',
    title: 'Styrketræning Lindelunden',
    date: '2025-11-12',
    startTime: '14:00',
    endTime: '17:00',
    location: 'Lindelundens træningscenter',
    cancelled: true,
    image: '/assets/gym2.jpg',
  },
  {
    id: 'a4',
    title: 'Cirkeltræning',
    date: '2025-11-14',
    startTime: '14:15',
    endTime: '15:00',
    location: 'RMI, Store Møllevej 5',
    image: '/assets/circuit.jpg',
  },
]
